### ISSUE TITLE
Array jobs have no resource limit on simultaneously running tasks

### ISSUE THREAD

**Issue by daajoe** [tlyphed/copperbench#3]
When running a job with a large number of instances, all possible resources for the user are requested.
That might lead to problems on HPC environments with billing and a bug in the software as all resources are easily used up.
A parameter and updating the array description to:
--array=1-{number of jobs}%MAXJOBS
might to the trick.

**Comment by tlyphed** [comment]
I added an option `max_parallel_jobs` which does that exactly that. In my tests it worked as expected.
