### ISSUE TITLE
Feature in config that copies the file to shm ($file{...}) and extracts it (say $uncompress_file{...})

### ISSUE THREAD

**Issue by daajoe** [tlyphed/copperbench#6]
Benchmarks take quite a lot of diskspace.
Hence, instances are oftentimes stored as compressed files (bz2, xz, or alike).
Would it be possible that a transparent uncompression step can be added. Similar to $file{...} feature in the config file?
See, e.g.:
https://github.com/daajoe/reprobench/blob/jkf_wip_pnode/lib/tcat.sh
for existing "transparent" uncompression.

**Comment by daajoe** [comment]
See: #8

**Comment by tlyphed** [comment]
thanks a lot
